jenkins:
  container_name: jenkins
  build: ./jenkins
  ports: 
   - 8080:8080
  volumes:
   - /home/core/final-exercise:/var/jenkins
   - /home/core/ssh/:/var/jenkins
node-app:
  container_name: node-app
  build: .
  ports:
   - 80:80
